image: tmaier/docker-compose:latest
services:
  - docker:dind

stages:
  - test
  - end2end

test:
  stage: test
  script:
    - docker-compose run --rm app npm run test
    - docker-compose run --rm api npm run test -- --runInBand
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

end2end:
  stage: end2end
  script:
    - docker-compose up -d
    - ./End2End/cypress-tests-runner.sh